### PR TITLE
Feature: Expected Value calculator

### PR DESCRIPTION
**Pull request by carlzoo**
Add a calculator to calculate the expected value of given odds

### CODE REVIEW

**Comment by ian-shepherd** [comment]
i will review in this weekend or next week

**Comment by ian-shepherd** [comment]
made following updates

- added the imports again but with comment that should ignore flake8 errors
realized an annoying future shortcoming without imports is instead of 
from pybettor import func1, func2
we would have to do
from pybettor.func1 import func1
from pybettor.func2 import func2
As we build out the library that isn't the best user experience. Based on what I read the actions should no longer fail witht he change I made

- renamed implied_probability to prob and added risk argument
- updated assertion errors
- changed test to match format of other tests
- changed version to 1.1.2

let me know if you see any issues with my changes. Will merge tomorrow

**Comment by carlzoo** [comment]
I had to remove 1 import because it was still causing flake8 issue. https://github.com/carlzoo/pybettor/actions/runs/5178677406/jobs/9330480620

Can you enable branch protection and run status checks for master? https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-status-checks-before-merging

This will ensure all the tests pass before the PR is merged into master.

**Comment by ian-shepherd** [comment]
alright the change I made passes the linting checks. As for your branch protection suggestion, I did enable that but it says no status checks found. My guess is we will need to update the workflow file to include the checks. I haven't used workflows much so a little out of my expertise but I will look more into it.

**Comment by carlzoo** [comment]
You will need to search for "build" under statuses. Try this setup:

chrome_69hLDvtv1k

**Comment by ian-shepherd** [comment]
yeah got it now. Looks like it just took time for the status to show up. Before I didn't have the option to search. Should be configured now

**Pull request merged**
